name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Unzip
      run: |
        apt-get update -qq && apt-get install -y -qq unzip
        rm -rf app
        unzip -q -o 486.zip
    
    - name: Build
      uses: android-actions/setup-android@v3
      with:
        api-level: 35
        ndk-version: 27.3.13750724
        cmake-version: 3.31.6
    
    - name: Gradle Build
      run: |
        cd app
        echo "sdk.dir=$ANDROID_HOME" > ../local.properties
        chmod +x ../gradlew
        ../gradlew assembleDebug --no-daemon
    
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: app/build/outputs/apk/debug/app-debug.apk
